# Generated by Django 3.2.4 on 2021-07-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('time', models.TimeField(auto_now_add=True)),
                ('income', models.IntegerField()),
                ('tax', models.FloatField()),
                ('expenses', models.IntegerField()),
                ('debt', models.IntegerField()),
                ('current_savings', models.FloatField()),
            ],
        ),
    ]
