# Generated by Django 3.2.4 on 2021-07-16 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='reference_id',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
