# Generated by Django 3.2.4 on 2021-08-17 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_details_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='home_owner',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
