# Generated by Django 3.2.4 on 2021-08-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_city_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income_expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.TextField(max_length=50)),
                ('grocery', models.FloatField()),
                ('housing', models.FloatField()),
                ('transportation', models.FloatField()),
                ('healthcare', models.FloatField()),
                ('misc', models.FloatField()),
            ],
        ),
    ]
